import {
  AccessibilityIcon,
  ArrowLeftRightIcon,
  BackpackIcon,
  CalendarIcon,
  CameraIcon,
  CloudSunIcon,
  DogIcon,
  DumbbellIcon,
  FlaskConicalIcon,
  HammerIcon,
  LeafIcon,
  PersonStandingIcon,
  RecycleIcon,
  ShieldIcon,
  ShoppingBagIcon,
  ThumbsUpIcon,
  TrainFrontIcon,
  TriangleIcon,
  TypeIcon,
  UserIcon,
  AlertTriangle,
  CompassIcon,
  SproutIcon,
  PlayCircleIcon,
  PiggyBankIcon,
  HeartIcon,
  DivideIcon,
  FacebookIcon,
  BuildingIcon,
  PieChartIcon,
  MessageCircleIcon,
  WifiIcon,
  DollarSignIcon,
  MousePointer2Icon,
  PaletteIcon,
  CodeIcon,
  SmartphoneIcon,
  SmileIcon,
  PanelLeftIcon,
  CoffeeIcon,
  RockingChairIcon,
  Gamepad2Icon,
  HomeIcon,
  MailIcon,
  MapIcon,
  FileIcon,
} from "lucide-react";

const categoryOptions = [
  {
    value: "accessibility",
    label: "Accessibility",
    icon: AccessibilityIcon,
  },
  {
    value: "account",
    label: "Accounts & access",
    icon: UserIcon,
  },
  {
    value: "animals",
    label: "Animals",
    icon: DogIcon,
  },
  {
    value: "arrows",
    label: "Arrows",
    icon: ArrowLeftRightIcon,
  },
  {
    value: "brands",
    label: "Brands",
    icon: FacebookIcon,
  },
  {
    value: "buildings",
    label: "Buildings",
    icon: BuildingIcon,
  },
  {
    value: "charts",
    label: "Charts",
    icon: PieChartIcon,
  },
  {
    value: "communication",
    label: "Communication",
    icon: MessageCircleIcon,
  },
  {
    value: "connectivity",
    label: "Connectivity",
    icon: WifiIcon,
  },
  {
    value: "currency",
    label: "Currency",
    icon: DollarSignIcon,
  },
  {
    value: "cursors",
    label: "Cursors",
    icon: MousePointer2Icon,
  },
  {
    value: "design",
    label: "Design",
    icon: PaletteIcon,
  },
  {
    value: "development",
    label: "Coding & development",
    icon: CodeIcon,
  },
  {
    value: "devices",
    label: "Devices",
    icon: SmartphoneIcon,
  },
  {
    value: "emoji",
    label: "Emoji",
    icon: SmileIcon,
  },
  {
    value: "files",
    label: "File icons",
    icon: FileIcon,
  },
  {
    value: "food-beverage",
    label: "Food & beverage",
    icon: CoffeeIcon,
  },
  {
    value: "furniture",
    label: "Furniture",
    icon: RockingChairIcon,
  },
  {
    value: "gaming",
    label: "Gaming",
    icon: Gamepad2Icon,
  },
  {
    value: "home",
    label: "Home",
    icon: HomeIcon,
  },
  {
    value: "layout",
    label: "Layout",
    icon: PanelLeftIcon,
  },
  {
    value: "mail",
    label: "Mail",
    icon: MailIcon,
  },
  {
    value: "maps",
    label: "Maps",
    icon: MapIcon,
  },
  {
    value: "maths",
    label: "Maths",
    icon: DivideIcon,
  },
  {
    value: "medical",
    label: "Medical",
    icon: HeartIcon,
  },
  {
    value: "money",
    label: "Money",
    icon: PiggyBankIcon,
  },
  {
    value: "multimedia",
    label: "Multimedia",
    icon: PlayCircleIcon,
  },
  {
    value: "nature",
    label: "Nature",
    icon: SproutIcon,
  },
  {
    value: "navigation",
    label: "Navigation",
    icon: CompassIcon,
  },
  {
    value: "notifications",
    label: "Notifications",
    icon: AlertTriangle,
  },
  {
    value: "people",
    label: "People",
    icon: PersonStandingIcon,
  },
  {
    value: "photography",
    label: "Photography",
    icon: CameraIcon,
  },
  {
    value: "science",
    label: "Science",
    icon: FlaskConicalIcon,
  },
  {
    value: "seasons",
    label: "Seasons",
    icon: LeafIcon,
  },
  {
    value: "security",
    label: "Security",
    icon: ShieldIcon,
  },
  {
    value: "shapes",
    label: "Shapes",
    icon: TriangleIcon,
  },
  {
    value: "shopping",
    label: "Shopping",
    icon: ShoppingBagIcon,
  },
  {
    value: "social",
    label: "Social",
    icon: ThumbsUpIcon,
  },
  {
    value: "sports",
    label: "Sports",
    icon: DumbbellIcon,
  },
  {
    value: "sustainability",
    label: "Sustainability",
    icon: RecycleIcon,
  },
  {
    value: "text",
    label: "Text formatting",
    icon: TypeIcon,
  },
  {
    value: "time",
    label: "Time & calendar",
    icon: CalendarIcon,
  },
  {
    value: "tools",
    label: "Tools",
    icon: HammerIcon,
  },
  {
    value: "transportation",
    label: "Transportation",
    icon: TrainFrontIcon,
  },
  {
    value: "travel",
    label: "Travel",
    icon: BackpackIcon,
  },
  {
    value: "weather",
    label: "Weather",
    icon: CloudSunIcon,
  },
];

export default categoryOptions;
